### PR TITLE
Optional instrument configuration in nxs.create()

### PR DESCRIPTION
**Pull request by jmborr**
### Goal
To provide a starting instrument configuration instead of the default `nxs.start.nxs` file. The purpose is to create a template with a closer geometry to that of the target instrument.  
For instance, to start with an instrument containing metadata entries that affect the geometry of the instrument. In this example, we include logs `det_arc1` and `det_arc2` that modify the position of the SNAP detectors. To create the intial configuration:
```python
# Prepare a generic template processed events NeXus file for SNAP. To be reused for all SNAP sample simulations
from mantid.simpleapi import LoadEventNexus, SaveNexus
# any recent SNAP run will do here
LoadEventNexus(Filename="/SNS/SNAP/IPTS-30008/nexus/SNAP_58769.nxs.h5",
               OutputWorkspace="events",
               MetaDataOnly=True)  #Do not load events
SaveNexus(InputWorkspace="events",
          Filename="./SNAP_template.nxs")

# Load the SNAP instrument template and adjust the detector arms. This should be done for every sample simulation.
from mantid.simpleapi import AddSampleLog, LoadInstrument, LoadNexus, SaveNexus
LoadNexus(Filename="./SNAP_template.nxs", OutputWorkspace="instrument")
detector1_rot, detector2_rot = -50, 105
AddSampleLog(Workspace="instrument",
             LogName='det_arc1', LogText= '{}'.format(detector1_rot), LogType='Number Series', NumberType='Double')
AddSampleLog(Workspace="instrument",
             LogName='det_arc2', LogText= '{}'.format(detector2_rot), LogType='Number Series', NumberType='Double')
SaveNexus(InputWorkspace="instrument",
          Filename="./instrument_adjusted.nxs")
```

Now we can create a template file starting with `./instrument_adjusted.nxs"` and inject the output data from a McVine simulation
```python
from mantid2mcvine.nxs.template import create
from mantid2mcvine.nxs.Events2Nxs import Events2Nxs
create("./SNAP_virtual_Definition.xml",
       ntotpixels,
       "./instrument_adjusted_stripped.nxs",
       instrument_template="./instrument_adjusted.nxs",
       workdir, pulse_time_end, nmonitors)

e2n = Events2Nxs("./instrument_adjusted_stripped.nxs",
                 ntotpixels, nmonitors)
e2n.write(events,
          tofbinsize,
          nxsfile="./SNAP_XXXX_McVine.nxs")
```

### CODE REVIEW

**Comment by jmborr** [comment]
@yxqd would you please review this PR for me?

**Comment by yxqd** [comment]
@jmborr I just updated master to restore github actions. Could you please merge the master so that the automatic test will run for your new branch, and see also if you can improve test_nxs.py to verify the generated nxs file?

**Comment by jmborr** [comment]
> @jmborr I just updated master to restore github actions. Could you please merge the master so that the automatic test will run for your new branch, and see also if you can improve test_nxs.py to verify the generated nxs file?

@yxqd I included some checks in the test. Can you please review again?

**Comment by yxqd** [comment]
Thanks @jmborr ! 
I am adding a test script based on https://github.com/mcvine/mantid2mcvine/blob/master/notebooks/demo.ipynb.

**Comment by jmborr** [comment]
@yxqd the coveralls test failed, I pushed a [tentative fix](https://github.com/mcvine/mantid2mcvine/pull/21/commits/472f99f797e05e8a5536ee588b1732836c49d2a5). Can you kick the GitHub actions again, please?

**Comment by jmborr** [comment]
@yxqd if this is to your satisfaction, can you merge the PR?

**Comment by yxqd** [comment]
@jmborr I added a test https://github.com/mcvine/mantid2mcvine/blob/b155b49373866e383e54884f5e5b4977a0793ef9/tests/test_workflow.py.
Could you please merge the master branch and see if that test pass? Thanks!

**Comment by jmborr** [comment]
> @jmborr I added a test https://github.com/mcvine/mantid2mcvine/blob/b155b49373866e383e54884f5e5b4977a0793ef9/tests/test_workflow.py. Could you please merge the master branch and see if that test pass? Thanks!

@yxqd If I understand you correctly, you want me to:
1. rebase my branch with `master`
2. manually run `test_workflow.py`

I did that and got this error:
```bash
DgsReduction-[Error] Error in execution of algorithm DgsReduction:
DgsReduction-[Error] Default facility must be set to SNS in order for reduction to work!
```
This I fixed by temporarily amending Mantid configuration so that SNS is the default facility. After this the test run to completion, I don't know if the results make sense, though.
I pushed the changes to remote. Can you please kick the GitHub Actions tests again?

**Comment by yxqd** [comment]
THanks, @jmborr. I just need to make one small change on "setFacility" call and the test passed!

**Pull request merged**
